version: '3.1'

services:
  db:
    image: mongo:3.4.19
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: alessandro 
      MONGO_INITDB_ROOT_PASSWORD: FogDirector 
      
  simulator:
    image: alessandro308/fogdirsim
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ${PWD}/src/config.py:/usr/src/app/src/config.py
    environment:
      DB_USER: alessandro
      DB_PSW: FogDirector
      DB_HOST: db
      DB_PORT: 27017


